baseURL = "https://blog.gennei.coffee/"
languageCode = "ja"
title = "gennei's blog"
publishDir = "docs"
googleAnalytics = "UA-106312693-1"
theme = "beautifulHugo"

[Params]
  rss = true

[Author]
  name = "gennei"
  github = "gennei"
  twitter = "gennei"
  instagram = "gennei"

[markup.goldmark.renderer]
  unsafe = true
