baseURL = "https://blog.gennei.coffee/"
languageCode = "ja"
title = "gennei's blog"
publishDir = "docs"
googleAnalytics = "UA-106312693-1"
theme = "noteworthy"
summaryLength = 4

[author]
	name = "gennei"

[taxonomies]
  tag = "tags"

[[menu.main]]
	identifier = "tags"
	name = "Tags"
	url = "/tags/"
	weight = 1

[params]
  rss = true
  name = "gennei"
  showReadMore = true
  github = "https://github.com/gennei"
  twitter = "https://twitter.com/gennei"
  instagram = "https://www.instagram.com/gennei"
  images = ["/img/ogp.jpg"]

[markup.goldmark.renderer]
  unsafe = true
