baseURL = "https://blog.gennei.coffee/"
googleAnalytics = "UA-106312693-1"
languageCode = "ja"
publishDir = "docs"
summaryLength = 4
theme = "noteworthy"
title = "gennei's blog"

[params.author]
name = "gennei"

[taxonomies]
tag = "tags"

[[menu.main]]
identifier = "tags"
name = "Tags"
url = "/tags/"
weight = 1

[params]
github = "https://github.com/gennei"
images = ["/img/ogp.jpg"]
instagram = "https://www.instagram.com/gennei"
name = "gennei"
rss = true
showReadMore = true
twitter = "https://twitter.com/gennei"

[markup.goldmark.renderer]
unsafe = true
