baseURL = "https://gennei.github.io/blog/"
languageCode = "ja"
title = "gennei's blog"
publishDir = "docs"

[Params]
  rss = true

[Author]
  name = "gennei"
  github = "gennei"
  twitter = "gennei"
  instagram = "gennei"
