baseURL = "https://blog.gennei.coffee/"
languageCode = "ja"
title = "gennei's blog"
publishDir = "docs"
googleAnalytics = "UA-106312693-1"
theme = "ananke"

[params]
  rss = true
  name = "gennei"
  github = "https://github.com/gennei"
  twitter = "https://twitter.com/gennei"
  instagram = "https://www.instagram.com/gennei"
  custom_css = ["css/custom.css"]
  recent_posts_number = 5

[markup.goldmark.renderer]
  unsafe = true
