name: Lighthouse

on:
  pull_request:
    branches:
      - master

jobs:
  lighthouse:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.101.0'
          extended: true

      - name: Build
        run: HUGO_ENV=production hugo --minify

      - name: Install Lighthouse CI
        run: npm install -g @lhci/cli@0.8.x

      - name: Run Lighthouse CI
        run: lhci autorun --upload.target=temporary-public-storage || echo "LHCI failed!"

      - name: Add Lighthouse report to PR
        uses: treosh/lighthouse-ci-action@v9
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          commentMode: pr
